Network:
  epochs: 800
  batch_size: 50
  n_steps: 12
  dataset: "CIFAR10"
  data_path: "/wy/dataset_wy/tiny_image/tiny2cifar10"
  log_path: "logs/tiny"
  backend: "cuda"
  optimizer: "SGD"
  lr: 0.0001
  weight_decay: 0.0005
  loss: "count+"
  gradient_type: "exponential"
  pooling_type: "adjusted_avg"
  n_class: 200
  # n_class: 10
  desired_count: 10
  undesired_count: 1
  tau_m: 7
  tau_s: 4
  tau_grad: 3.5

  model_import: "networks.vgg"
